### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by winkerbie** [mrfearless/APISearch-Plugin-x64#1]
right-click and selecting "search with google" does nothing, default browser is chrome???

**Comment by mrfearless** [comment]
Yes this functionality has been included in x64dbg with the Help on Symbolic Name option that appears when you right click on a call < windown api name function> line. It uses the default web browser to search google for that symbolic name. And due to some changes in x64dbg (64bit version) over time this plugin's ability to check for the name after the call instruction meant it no longer worked. I tested the 32 bit version and the plugin still seems to work - i might have a look at trying to get this to work for 64bit version if i have time.

**Comment by winkerbie** [comment]
It would be helpful if you could fix it for x64 bit debugger, the internal version is a bit unreliable your plugin searches more than just google, which would be helpful. Thanks

**Comment by mrfearless** [comment]
Ok, i have updated the plugin - might have been a bug in the way i was handling the menu entries in all x64 plugins i wrote - so i recompiled them (x64 versions). Seemed to work. Let me know how you get on with it. Latest release is in the release folder: APISearch.dp64 or from the releases section (uploaded a newer zip)

**Comment by winkerbie** [comment]
Works well, thank you for that :)

Its much quicker

**Comment by mrfearless** [comment]
Your welcome. I'll close the issue for now.
